// AUTO-GENERATED by scripts/build-theme.ts from the Ink & Signal DTCG tokens.
// Do not edit by hand — run `npm run build:theme`. See ADR-0006.
/* eslint-disable */

export const lightColors = {
  "bg.base": "#F3F5F6",
  "bg.surface": "#FFFFFF",
  "bg.elevated": "#FFFFFF",
  "bg.subtle": "#E8ECEF",
  "bg.pressed": "#EDF1F3",
  "text.primary": "#10161B",
  "text.secondary": "#46525B",
  "text.muted": "#7A8791",
  "accent.default": "#0E8C7D",
  "accent.pressed": "#0A6E62",
  "accent.on": "#FFFFFF",
  "accent.surface": "#DCF0EC",
  "status.done": "#2E9E5B",
  "status.overdue": "#D64545",
  "status.overdueSurface": "#F9E3E3",
  "status.blocked": "#7A8791",
  "border.default": "#DFE4E8",
  "priority.low": "#3E7FC1",
  "priority.medium": "#DD8425",
  "priority.high": "#D64545"
} as const;

export const darkColors = {
  "bg.base": "#000000",
  "bg.surface": "#111417",
  "bg.elevated": "#181D21",
  "bg.subtle": "#1A2024",
  "bg.pressed": "#1E2529",
  "text.primary": "#E8EEF2",
  "text.secondary": "#97A5B0",
  "text.muted": "#667582",
  "accent.default": "#3FC0A9",
  "accent.pressed": "#62D1BD",
  "accent.on": "#000000",
  "accent.surface": "#12332E",
  "status.done": "#4FBA79",
  "status.overdue": "#E46A6A",
  "status.overdueSurface": "#3A2226",
  "status.blocked": "#667582",
  "border.default": "#262D33",
  "priority.low": "#5D9BD4",
  "priority.medium": "#E29A47",
  "priority.high": "#E46A6A"
} as const;

export const spacing = {
  "xs": 4,
  "sm": 8,
  "md": 12,
  "lg": 16,
  "xl": 24,
  "xxl": 32
} as const;

export const radii = {
  "sm": 4,
  "md": 6,
  "lg": 10,
  "xl": 14,
  "pill": 999
} as const;

export const typography = {
  "display": {
    "fontFamily": "IBM Plex Sans",
    "fontSize": 28,
    "fontWeight": "700",
    "lineHeight": 34
  },
  "title": {
    "fontFamily": "IBM Plex Sans",
    "fontSize": 17,
    "fontWeight": "600",
    "lineHeight": 22
  },
  "body": {
    "fontFamily": "IBM Plex Sans",
    "fontSize": 15,
    "fontWeight": "400",
    "lineHeight": 20
  },
  "label": {
    "fontFamily": "IBM Plex Sans",
    "fontSize": 13,
    "fontWeight": "500",
    "lineHeight": 18
  },
  "caption": {
    "fontFamily": "IBM Plex Sans",
    "fontSize": 11,
    "fontWeight": "600",
    "lineHeight": 14
  }
} as const;

export type ColorToken = keyof typeof lightColors;
