/**
 * Compile the DTCG design tokens into an RN-safe TypeScript module that the
 * Restyle theme consumes (ADR-0006). Run with `npm run build:theme`.
 *
 *   design/exports/.../tokens.ink-signal.dtcg.json   (source of truth)
 *        -> expandModes (light/dark, this repo)       compile.ts
 *        -> Style Dictionary  (alias resolution + colour transform)
 *        -> src/theme/tokens.generated.ts             (committed output)
 *
 * The colour transform (`color/rnSafe`) is where the ADR's build-time
 * "Oklch/P3 -> RN-safe colour" conversion happens; see color.ts. The output is
 * committed so the RN bundle never depends on Style Dictionary at runtime, and a
 * unit test pins a few known values so a broken pipeline fails CI.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import StyleDictionary from "style-dictionary";
import { toRnHex } from "../src/theme/color.ts";
import { expandModes, parseDimension, type DtcgNode, type Mode } from "../src/theme/compile.ts";

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(
  here,
  "../../design/exports/pass-01-system/html/tokens.ink-signal.dtcg.json",
);
const OUT = resolve(here, "../src/theme/tokens.generated.ts");

StyleDictionary.registerTransform({
  name: "color/rnSafe",
  type: "value",
  transitive: true, // resolve aliases first, then convert the resolved colour
  filter: (token) => (token.$type ?? token.type) === "color",
  transform: (token) => toRnHex(String(token.$value ?? token.value)),
});

interface Leaf {
  path: string[];
  value: unknown;
}

async function resolveTokens(dtcg: DtcgNode, mode: Mode): Promise<Leaf[]> {
  const sd = new StyleDictionary({
    tokens: expandModes(dtcg, mode) as Record<string, unknown>,
    usesDtcg: true,
    log: { verbosity: "silent" },
    platforms: { rn: { transforms: ["color/rnSafe"] } },
  });
  // getPlatformTokens returns { tokens, allTokens, tokenMap }; allTokens is the
  // flat list of resolved leaves, each carrying its dotted `path` and `$value`.
  const { allTokens } = (await sd.getPlatformTokens("rn")) as {
    allTokens: Array<{ path: string[]; $value: unknown }>;
  };
  return allTokens.map((t) => ({ path: t.path, value: t.$value }));
}

function colorsOf(all: Leaf[]): Record<string, string> {
  const out: Record<string, string> = {};
  for (const { path, value } of all) {
    if (path[0] !== "color") continue;
    out[path.slice(1).join(".")] = String(value);
  }
  return out;
}

function dimsOf(all: Leaf[], group: string): Record<string, number> {
  const out: Record<string, number> = {};
  for (const { path, value } of all) {
    if (path[0] !== group || path.length !== 2) continue;
    out[path[1] as string] = parseDimension(String(value));
  }
  return out;
}

interface TypeToken {
  fontFamily: string;
  fontSize: number;
  fontWeight: string;
  lineHeight: number;
}

function typographyOf(all: Leaf[]): Record<string, TypeToken> {
  const out: Record<string, TypeToken> = {};
  for (const { path, value } of all) {
    if (path[0] !== "type" || path.length !== 2) continue;
    const v = value as { fontFamily: string; fontSize: string; fontWeight: number; lineHeight: string };
    out[path[1] as string] = {
      fontFamily: v.fontFamily,
      fontSize: parseDimension(v.fontSize),
      fontWeight: String(v.fontWeight),
      lineHeight: parseDimension(v.lineHeight),
    };
  }
  return out;
}

function serialise(name: string, value: unknown): string {
  return `export const ${name} = ${JSON.stringify(value, null, 2)} as const;\n`;
}

async function main(): Promise<void> {
  const dtcg = JSON.parse(readFileSync(SOURCE, "utf8")) as DtcgNode;
  const light = await resolveTokens(dtcg, "light");
  const dark = await resolveTokens(dtcg, "dark");

  const banner =
    "// AUTO-GENERATED by scripts/build-theme.ts from the Ink & Signal DTCG tokens.\n" +
    "// Do not edit by hand — run `npm run build:theme`. See ADR-0006.\n" +
    "/* eslint-disable */\n\n";

  const body =
    serialise("lightColors", colorsOf(light)) +
    "\n" +
    serialise("darkColors", colorsOf(dark)) +
    "\n" +
    serialise("spacing", dimsOf(light, "space")) +
    "\n" +
    serialise("radii", dimsOf(light, "radius")) +
    "\n" +
    serialise("typography", typographyOf(light)) +
    "\n" +
    "export type ColorToken = keyof typeof lightColors;\n";

  writeFileSync(OUT, banner + body);
  const count = Object.keys(colorsOf(light)).length;
  console.log(`build-theme: wrote ${count} colours x2 modes to ${OUT}`);
}

await main();
